---
- hosts: all
  become: true
  tasks:

  - name: Add docker-ce repository
    yum_repository:
      name: docker-ce
      description: "docker-ce repository"
      baseurl: https://download.docker.com/linux/centos/8/x86_64/stable/
      gpgcheck: false

  - name: Add kubernetes repository
    yum_repository:
      name: kubernetes
      description: "Kubernetes repository"
      baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      gpgcheck: false

  - name: Install docker-ce
    yum:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - docker-ce
    notify:
      - docker status

  - name: Add vagrant user to docker group
    user:
      name: vagrant
      groups: docker
      append: true

# Kubelet will not start if swap is enabled; disable swap.

  - name: Remove swapfile from /etc/fstab
    mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
    with_items:
      - swap
      - none

  - name: Disable swap
    command: swapoff -a
    when: ansible_swaptotal_mb > 0

  - name: Install Kubernetes binaries
    yum:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
        - kubelet
        - kubeadm
        - kubectl

  - name: Check if kubelet has been configured
    stat:
      path: /etc/default/kubelet
    register: kubelet_configured

  - name: Configure node ip
    lineinfile:
      path: /etc/default/kubelet
      line: KUBELET_EXTRA_ARGS=--node-ip={{ node_ip }}
      create: yes
    when: not kubelet_configured.stat.exists

  - name: Restart kubelet
    service:
      name: kubelet
      daemon_reload: yes
      state: restarted
    when: not kubelet_configured.stat.exists

  - name: Ensure kubelet service is running and enabled
    service:
      name: kubelet
      enabled: true
      state: started

  - name: Ensure docker daemon is running and enabled
    service:
      name: docker
      enabled: true
      state: started

  - name: Copy the join command to server location
    copy: src=join-command dest=/tmp/join-command.sh mode=0777
    when: not kubelet_configured.stat.exists

  - name: Join the node to cluster
    command: /bin/sh /tmp/join-command.sh
    when: not kubelet_configured.stat.exists

  handlers:
    - name: docker status
      service: name=docker state=started

